name: Docker publish

on:
  push:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
        name: Release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          use_github_release_notes: true

  update-changelog:
    runs-on: ubuntu-latest
    needs: release-on-push
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get previous tag
        id: previousTag
        run: |
          name=$(git --no-pager tag --sort=creatordate --merged ${{ github.ref_name }} | tail -2 | head -1)
          echo "previousTag: $name"
          echo "previousTag=$name" >> $GITHUB_ENV

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ needs.release-on-push.outputs.tag_name }}
          toTag: ${{ env.previousTag }}

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: "chore(release): update CHANGELOG.md for ${{ needs.release-on-push.outputs.tag_name  }} [skip ci] [norelease]"
          file_pattern: CHANGELOG.md

  build:
    runs-on: ubuntu-latest
    needs: release-on-push
    steps:
      - name: Maximize build space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          docker-images: false

      - name: Clean docker image cache
        run: |
          docker image rm -f \
          $( \
            docker image ls -a | \
            grep -v "buildkit" | \
            grep -v "ubuntu.*22\.04" | \
            awk 'NR>1 {print $3}'
          )

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mnb3000/runpod-sdnext
          flavor: |
            latest=auto
          tags: |
            type=semver,pattern={{version}},value=${{ needs.release-on-push.outputs.tag_name  }}
            type=semver,pattern={{major}}.{{minor}},value=${{ needs.release-on-push.outputs.tag_name  }}
            type=semver,pattern={{major}},value=${{ needs.release-on-push.outputs.tag_name  }}

      - name: Build and push
        uses: docker/bake-action@v4
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          targets: default
          push: true
        env:
          RELEASE: ${{ needs.release-on-push.outputs.tag_name }}
